# image:
#   repository: velero/velero
#   tag: v1.2.0
#   pullPolicy: IfNotPresent

# Resource requests/limits to specify for the Velero deployment. Optional.
resources: {}

initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  provider: gcp
  backupStorageLocation:
    default: true
    name: gcp
    bucket: etcd-io-backups
    prefix: velero
    config:
      serviceAccount: prod-gke-velero-sa@etcd-io.iam.gserviceaccount.com

  volumeSnapshotLocation:
    name: gcp

rbac:
  create: true
  clusterAdministrator: true

serviceAccount:
  server:
    create: true
    name: velero
    annotations:
      iam.gke.io/gcp-service-account: prod-gke-velero-sa@etcd-io.iam.gserviceaccount.com

credentials:
  useSecret: false

snapshotsEnabled: true

deployNodeAgent: true

schedules:
  gcp:
    schedule: "30 9 * * *"
    template:
      storageLocation: gcp
      includeClusterResources: true
      includedNamespaces:
        - "*"
      includedResources:
        - "*"
      snapshotVolumes: true
      ttl: "720h"
