apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: discovery-server
  labels:
    prometheus: prometheus-operator
    role: alert-rules
    {{- toYaml .Values.prometheusRules.labels | nindent 4 }}
spec:
  groups:
    - name: discovery-server.rules
      rules:
        {{ range $index, $promRule := .Values.prometheusRules.recording -}}
        - expr:  {{ $promRule.expr }}
          record: {{ $promRule.record }}
          labels:
            {{- toYaml $promRule.labels | nindent 12 }}
        {{ end }}
        {{ range $index, $promRule := .Values.prometheusRules.alerting -}}
        - expr:  {{ $promRule.expr }}
          alert: {{ $promRule.alert }}
          for: {{ $promRule.for }}
          labels:
            {{- toYaml $promRule.labels | nindent 12 }}
        {{ end }}
