apiVersion: v1
kind: Service
metadata:
  name: {{ include "discoveryserver.fullname" . }}
  labels:
    {{- include "discoveryserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8087
      protocol: TCP
      name: http
  selector:
    {{- include "discoveryserver.selectorLabels" . | nindent 4 }}
