controller:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 18
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
  replicaCount: 3
  minAvailable: 2
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
