controller:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 18
    targetCPUUtilizationPercentage: "90"
    targetMemoryUtilizationPercentage: "90"
  replicaCount: 3
  minAvailable: 2
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
