apiVersion: v2
appVersion: "0.56.2"
description: Prometheus operator helm chart
name: kube-prometheus-stack
version: 35.2.0
dependencies:
  - name: kube-prometheus-stack
    version: "35.2.0"
    repository: "@prometheus-community"
