kube-prometheus-stack:
  grafana:
    adminPassword: '<PASSWORD>'
  alertmanager:
    config: 
      receivers:
      - name: blackhole
      - name: your-org-slack
        slack_configs:
        - api_url: '<slack api url secret>'
          send_resolved: true
          channel: '#alerts'
          username: alertmanager
secrets:
  auth: "kube-prometheus-stack:<ENCRYPTED PASSWORD>"
  GF_AUTH_GOOGLE_CLIENT_ID: "<secret>" # optional 
  GF_AUTH_GOOGLE_CLIENT_SECRET: "<secret>" # optional 
